window.RESEARCH_PAPERS = [
  {
    id: 1,
    title: "AI-Supported Mental Health Triage for Doctoral Researchers",
    year: 2024,
    countries: ["United Kingdom", "Canada"],
    domain: "PhD wellbeing",
    methods: ["transformer NLP", "survey", "risk modelling"],
    keywords: ["doctoral students", "mental health", "AI support", "wellbeing", "triage"],
    abstract: "Examines whether language models can identify risk patterns in doctoral student wellbeing narratives and route students to support resources.",
    population: "doctoral researchers",
    gapSignals: ["limited evidence outside English-speaking universities", "few longitudinal studies", "limited intervention validation"]
  },
  {
    id: 2,
    title: "Graduate Student Burnout Detection from Reflective Journals",
    year: 2023,
    countries: ["United States"],
    domain: "PhD wellbeing",
    methods: ["semantic embeddings", "journaling analysis"],
    keywords: ["graduate burnout", "wellbeing", "stress", "embeddings"],
    abstract: "Uses sentence embeddings to detect burnout markers in graduate student reflective journals across one academic year.",
    population: "graduate students",
    gapSignals: ["single-country sample", "limited comparison with non-AI screening"]
  },
  {
    id: 3,
    title: "Climate Adaptation Governance in Small Island Research Systems",
    year: 2021,
    countries: ["Fiji", "Australia"],
    domain: "climate adaptation",
    methods: ["policy review", "interviews"],
    keywords: ["island adaptation", "governance", "coastal resilience"],
    abstract: "Studies policy coordination and adaptation capacity in island states facing sea-level rise and climate-linked migration.",
    population: "small island states",
    gapSignals: ["few machine learning studies", "weak regional comparison"]
  },
  {
    id: 4,
    title: "Low-Resource Clinical NLP for Community Health Records",
    year: 2022,
    countries: ["India", "Kenya"],
    domain: "healthcare NLP",
    methods: ["multilingual NLP", "few-shot learning"],
    keywords: ["low-resource NLP", "clinical notes", "community health"],
    abstract: "Investigates multilingual natural language processing for sparse and noisy clinical records from community health settings.",
    population: "community healthcare systems",
    gapSignals: ["little work on African languages", "few reproducible benchmark datasets"]
  },
  {
    id: 5,
    title: "Peer Review Bias and Gendered Language in STEM Publishing",
    year: 2020,
    countries: ["Germany", "Netherlands", "United States"],
    domain: "research evaluation",
    methods: ["text mining", "bias analysis"],
    keywords: ["peer review", "gender bias", "publishing", "language"],
    abstract: "Explores whether evaluation language used in STEM peer review reflects gendered assumptions and prestige effects.",
    population: "journal reviewers",
    gapSignals: ["limited evidence from Global South journals", "few intervention studies"]
  },
  {
    id: 6,
    title: "Urban Heat Vulnerability Mapping with Remote Sensing in African Cities",
    year: 2024,
    countries: ["South Africa", "Nigeria", "Ghana"],
    domain: "urban climate",
    methods: ["remote sensing", "spatial ML"],
    keywords: ["urban heat", "adaptation", "African cities", "remote sensing"],
    abstract: "Maps heat vulnerability and adaptation readiness in rapidly growing African cities using satellite imagery and urban indicators.",
    population: "urban residents",
    gapSignals: ["limited inclusion of informal settlements", "few long-term comparative studies"]
  },
  {
    id: 7,
    title: "Large Language Models for Systematic Review Screening in Education",
    year: 2025,
    countries: ["Singapore", "United Kingdom"],
    domain: "evidence synthesis",
    methods: ["LLM classification", "active learning"],
    keywords: ["systematic review", "education research", "screening automation"],
    abstract: "Tests LLM-assisted abstract screening workflows for faster evidence synthesis in education and learning sciences.",
    population: "education research literature",
    gapSignals: ["limited transparency reporting", "little testing on multilingual corpora"]
  },
  {
    id: 8,
    title: "Doctoral Attrition Signals Across Research-Intensive Universities",
    year: 2019,
    countries: ["Australia", "United Kingdom"],
    domain: "PhD wellbeing",
    methods: ["institutional analytics", "survival analysis"],
    keywords: ["doctoral attrition", "completion", "risk factors", "universities"],
    abstract: "Identifies patterns in doctoral attrition across research-intensive institutions and connects them to supervisory and workload factors.",
    population: "doctoral candidates",
    gapSignals: ["limited mental health variables", "limited data from low-income countries"]
  },
  {
    id: 9,
    title: "Responsible AI Adoption in Higher Education Student Support",
